import type {
  SeriesEntry,
  PageImage,
} from "./types";
import { API_BASE } from "./constants";

// World entry with optional reference image
export interface WorldEntry {
  file: string;
  image: string | null;
}

// Series content manifest (generated by scripts/sync.js)
export interface ContentManifest {
  generated: string;
  chapters: {
    number: number;
    files: string[];
    media: string[];
    pages: (number | { number: number; files: string[] })[];
  }[];
  arcs: {
    number: number;
    files: string[];
    sources: string[];
  }[];
  sources: string[];
  modules: string[];
  meta: string[];
  world: {
    characters: WorldEntry[];
    locations: WorldEntry[];
    elements: WorldEntry[];
  };
}

// Cache for manifests
const manifestCache: Record<string, ContentManifest> = {};

export async function getContentManifest(seriesId: string): Promise<ContentManifest | null> {
  if (manifestCache[seriesId]) {
    return manifestCache[seriesId];
  }

  try {
    const res = await fetch(`${API_BASE}/${seriesId}/manifest.json`);
    if (!res.ok) return null;
    const manifest = await res.json();
    manifestCache[seriesId] = manifest;
    return manifest;
  } catch {
    return null;
  }
}

// Fetch series list - always returns array
export async function getSeriesList(): Promise<SeriesEntry[]> {
  try {
    const res = await fetch(`${API_BASE}/index.json`, { cache: 'no-store' });
    if (!res.ok) return [];
    const data = await res.json();
    // Handle legacy single-object format for backward compatibility
    return Array.isArray(data) ? data : [data];
  } catch {
    return [];
  }
}

// Get the first/default series (backward compatibility)
export async function getSeriesManifest(): Promise<SeriesEntry | null> {
  const list = await getSeriesList();
  return list[0] || null;
}

export async function discoverChapters(seriesId: string): Promise<number[]> {
  const manifest = await getContentManifest(seriesId);
  if (manifest) {
    return manifest.chapters.map((c) => c.number);
  }
  return [];
}

export async function getSeriesEntry(
  seriesId: string
): Promise<SeriesEntry | null> {
  const list = await getSeriesList();
  const entry = list.find(s => s.id === seriesId);
  if (!entry) return null;

  // Auto-discover chapters if not provided in manifest
  if (!entry.chapters || entry.chapters.length === 0) {
    entry.chapters = await discoverChapters(seriesId);
  }

  return entry;
}

export async function getSeriesMetadata(seriesId: string): Promise<string> {
  const res = await fetch(`${API_BASE}/${seriesId}/series.md`);
  if (!res.ok) return "";
  return res.text();
}

export async function getChapterDraft(
  seriesId: string,
  chapterNum: number
): Promise<string> {
  const res = await fetch(
    `${API_BASE}/${seriesId}/chapters/${chapterNum}/draft.md`
  );
  if (!res.ok) return "";
  return res.text();
}

// Workflow files in order of the writing process
export const WORKFLOW_FILES = [
  { name: "objective.md", label: "Objective", description: "Chapter goals and direction" },
  { name: "concept.md", label: "Concept", description: "High-level chapter concept" },
  { name: "memory.md", label: "Memory", description: "Context from previous chapters" },
  { name: "route.md", label: "Route", description: "Semantic route and narrative beats" },
  { name: "draft.md", label: "Draft", description: "The chapter prose" },
  { name: "review.md", label: "Review", description: "Review against route and memory" },
  { name: "summary.md", label: "Summary", description: "Summary for future chapters" },
] as const;

// General source files (in sources/)
export const SOURCE_FILES = [
  { name: "protagonist.md", label: "Protagonist" },
  { name: "world.md", label: "World" },
] as const;

// Arc-specific source files (in sources/{n}/)
export const ARC_SOURCE_FILES = [
  { name: "characters.md", label: "Characters" },
  { name: "setting.md", label: "Setting" },
] as const;

// Arc workflow files (in arcs/{n}/)
export const ARC_FILES = [
  { name: "arc.md", label: "Arc Overview" },
  { name: "concept.md", label: "Concept" },
  { name: "formula.md", label: "Formula" },
  { name: "progress.md", label: "Progress" },
] as const;

export async function getChapterWorkflowFile(
  seriesId: string,
  chapterNum: number,
  fileName: string
): Promise<string> {
  const res = await fetch(
    `${API_BASE}/${seriesId}/chapters/${chapterNum}/${fileName}`
  );
  if (!res.ok) return "";
  return res.text();
}

export async function getChapterWorkflowFiles(
  seriesId: string,
  chapterNum: number
): Promise<Record<string, string>> {
  const results: Record<string, string> = {};

  await Promise.all(
    WORKFLOW_FILES.map(async (file) => {
      const content = await getChapterWorkflowFile(seriesId, chapterNum, file.name);
      if (content) {
        results[file.name] = content;
      }
    })
  );

  return results;
}

export function getMusicPath(seriesId: string, chapterNum: number): string {
  return `${API_BASE}/${seriesId}/chapters/${chapterNum}/media/background-music.mp3`;
}

export function getPageImageUrl(seriesId: string, chapterNum: number, pageNum: number): string {
  return `${API_BASE}/${seriesId}/chapters/${chapterNum}/pages/${pageNum}/page.jpg`;
}

export async function getChapterPages(seriesId: string, chapterNum: number): Promise<number[]> {
  const manifest = await getContentManifest(seriesId);
  if (!manifest) return [];
  const chapter = manifest.chapters.find(c => c.number === chapterNum);
  return (chapter?.pages || []).map(p => typeof p === "object" ? p.number : p);
}

export async function getAllPageImages(
  seriesId: string,
  chapters: number[]
): Promise<PageImage[]> {
  const manifest = await getContentManifest(seriesId);
  if (!manifest) return [];

  const images: PageImage[] = [];
  for (const chapter of manifest.chapters) {
    if (!chapters.includes(chapter.number)) continue;
    for (const p of (chapter.pages || [])) {
      const pageNum = typeof p === "object" ? p.number : p;
      images.push({
        src: getPageImageUrl(seriesId, chapter.number, pageNum),
        chapterNum: chapter.number,
        pageNum,
      });
    }
  }
  return images;
}

export async function getSourceFile(
  seriesId: string,
  path: string
): Promise<string> {
  const res = await fetch(`${API_BASE}/${seriesId}/${path}`);
  if (!res.ok) return "";
  return res.text();
}

export function extractTitleFromMarkdown(content: string): string {
  const match = content.match(/^#\s+(?:Chapter\s+\d+:?\s*)?(.+)$/m);
  return match ? match[1].trim() : "";
}

export function stripTitleFromMarkdown(content: string): string {
  // Remove the first heading (# Chapter X: Title) to avoid duplicate titles
  return content.replace(/^#\s+(?:Chapter\s+\d+:?\s*)?.+\n+/, "").trim();
}

export function parseSeriesMetadata(content: string) {
  const lines = content.split("\n");
  const metadata: Record<string, string> = {};

  let currentSection = "";
  for (const line of lines) {
    if (line.startsWith("## ")) {
      currentSection = line.replace("## ", "").trim().toLowerCase();
    } else if (currentSection && line.trim()) {
      if (!metadata[currentSection]) {
        metadata[currentSection] = line.trim();
      }
    }
  }

  return metadata;
}

export interface ChapterInfo {
  number: number;
  title: string;
  wordCount: number;
  readingTime: number; // in minutes
}

export function calculateReadingTime(content: string): { wordCount: number; readingTime: number } {
  // Remove markdown syntax for accurate word count
  const plainText = content
    .replace(/^#{1,6}\s+/gm, '') // headers
    .replace(/\*\*|__/g, '') // bold
    .replace(/\*|_/g, '') // italic
    .replace(/\[([^\]]+)\]\([^)]+\)/g, '$1') // links
    .replace(/!\[([^\]]*)\]\([^)]+\)/g, '') // images
    .replace(/```[\s\S]*?```/g, '') // code blocks
    .replace(/`[^`]+`/g, '') // inline code
    .replace(/^\s*[-*+]\s+/gm, '') // list markers
    .replace(/^\s*\d+\.\s+/gm, '') // numbered lists
    .replace(/>\s+/g, '') // blockquotes
    .replace(/---+/g, '') // horizontal rules
    .trim();

  const words = plainText.split(/\s+/).filter(word => word.length > 0);
  const wordCount = words.length;

  // Average reading speed: 200-250 WPM, using 220 for web novel content
  const readingTime = Math.ceil(wordCount / 220);

  return { wordCount, readingTime: Math.max(1, readingTime) };
}

export async function getChapterInfo(
  seriesId: string,
  chapterNum: number
): Promise<ChapterInfo> {
  const draft = await getChapterDraft(seriesId, chapterNum);
  const title = extractTitleFromMarkdown(draft);
  const { wordCount, readingTime } = calculateReadingTime(draft);
  return { number: chapterNum, title, wordCount, readingTime };
}

export async function getAllChapterInfo(
  seriesId: string,
  chapters: number[]
): Promise<ChapterInfo[]> {
  const infos = await Promise.all(
    chapters.map((num) => getChapterInfo(seriesId, num))
  );
  return infos.sort((a, b) => a.number - b.number);
}

export interface ChapterVideo {
  chapterNumber: number;
  title: string;
  thumbnail?: string;
  desktopSrc?: string;
  mobileSrc?: string;
}

export async function getAllChapterVideos(
  seriesId: string,
  manifest: ContentManifest
): Promise<ChapterVideo[]> {
  const videos: ChapterVideo[] = [];

  await Promise.all(
    manifest.chapters.map(async (chapter) => {
      const desktopPath = `${API_BASE}/${seriesId}/chapters/${chapter.number}/media/chapter-video-desktop.mp4`;
      const mobilePath = `${API_BASE}/${seriesId}/chapters/${chapter.number}/media/chapter-video-mobile.mp4`;

      let hasDesktop = false;
      let hasMobile = false;

      try {
        const [dRes, mRes] = await Promise.all([
          fetch(desktopPath, { method: "HEAD" }).catch(() => null),
          fetch(mobilePath, { method: "HEAD" }).catch(() => null),
        ]);
        hasDesktop = dRes?.ok ?? false;
        hasMobile = mRes?.ok ?? false;
      } catch {
        return;
      }

      if (!hasDesktop && !hasMobile) return;

      const draftRes = await fetch(`${API_BASE}/${seriesId}/chapters/${chapter.number}/draft.md`);
      let title = `Chapter ${chapter.number}`;
      if (draftRes.ok) {
        const content = await draftRes.text();
        const match = content.match(/^#\s+(?:Chapter\s+\d+:?\s*)?(.+)$/m);
        if (match) title = match[1].trim();
      }

      const firstPage = chapter.pages?.[0];
      const firstPageNum = typeof firstPage === "object" ? firstPage.number : firstPage;
      const thumbnail = firstPageNum
        ? `${API_BASE}/${seriesId}/chapters/${chapter.number}/pages/${firstPageNum}/page.jpg`
        : undefined;

      videos.push({
        chapterNumber: chapter.number,
        title,
        thumbnail,
        desktopSrc: hasDesktop ? desktopPath : undefined,
        mobileSrc: hasMobile ? mobilePath : undefined,
      });
    })
  );

  return videos.sort((a, b) => a.chapterNumber - b.chapterNumber);
}
